# Generated by Django 4.2.3 on 2023-09-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
