# Generated by Django 4.2.3 on 2023-09-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_born',
            new_name='date_of_birth',
        ),
    ]
